---
- name: Generate inmemory inventory
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - block:

      - name: Fetch Instance Info
        os_server_info:
          cloud: "{{ openstack_cloud | default('openstack') }}"
          region_name: "{{ openstack_region | default('regionOne') }}"
        register: r_instances

      - name: Add host(s) to inventory
        add_host:
          name: "{{ __instance.public_v4 }}"
          group: 
            - "{{ __instance.metadata.group }}"
            - "{{ __instance.metadata.deployment_name }}"
        loop: "{{ r_instances.openstack_servers }}"
        loop_control:
          loop_var: __instance


    - name: Output the in-memory inventory
      block:

      - name: Print hosts to STDOUT
        debug:
          msg:
            - "name: {{ __instance.public_v4 }}"
            - "group: {{ __instance.metadata.group }}"
        loop: "{{ r_instances.openstack_servers }}"
        loop_control:
          loop_var: __instance

      - name: Generate lab static inventory file
        template:
          src: lab_inventory.j2
          dest: "/tmp/my_inventory"
        delegate_to: localhost

      - name: Output location of example of inventory
        debug:
          msg: Your inventory was output to /tmp/my_inventory

  tags:
    - openstack-inventory
    - must  
